import React from "react"
import { HorizontalNav } from "./HorizontalNav"
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  HorizontalNav,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=7514-12157&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showDivider: figma.boolean("Show divider"),
      showLeftOverflowArrow: figma.boolean("Show Left Overflow arrow"),
      showRightOverflowArrow: figma.boolean("Show Right Overflow arrow"),
      type: figma.enum("Type", {
        Main: "main",
        Subnav: "subnav",
      }),
    },
    example: (props) => <HorizontalNav />,
  },
)
