import { HorizontalSubnavItem } from "./HorizontalSubnavItem"
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  HorizontalSubnavItem,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2104-7269&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      navItem: figma.string("✏️ Nav item"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Selected: "selected",
      }),
    },
    example: (props) => <HorizontalSubnavItem />,
  },
)
