import React from "react"
import { LeftNav } from "./LeftNav"
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  LeftNav,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2104-7106&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showProductTitleArea: figma.boolean("Show Product title area"),
    },
    example: (props) => <LeftNav />,
  },
)
