import React from "react"
import { SubnavOverflowArrow } from "./SubnavOverflowArrow"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SubnavOverflowArrow,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2104-7283&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      position: figma.enum("Position", {
        Left: "left",
        Right: "right",
        Position3: "position3",
        Position4: "position4",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Disabled: "disabled",
      }),
    },
    example: (props) => <SubnavOverflowArrow />,
  },
)
