import React from "react"
import { ClipboardCopyInlineCompact } from "./ClipboardCopyInlineCompact"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ClipboardCopyInlineCompact,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=9914-75768&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      type: figma.enum("Type", {
        Default: "default",
        "Additional Action": "additional-action",
        Sentence: "sentence",
        Type4: "type4",
        Type5: "type5",
        Type6: "type6",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
      }),
    },
    example: (props) => <ClipboardCopyInlineCompact />,
  },
)
