import React from 'react';
import { ClipBoardCopy } from './ClipBoardCopy';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ClipBoardCopy,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=9914-75835&t=IzSunfrnw18ti37Y-11',
  {
    props: {
      expandable: figma.boolean('Expandable'),
      state: figma.enum('State', {
        Default: 'default',
        'Read only': 'read-only',
        Expanded: 'expanded',
        Hover: 'hover',
        Active: 'active'
      })
    },
    example: (props) => <ClipBoardCopy />
  }
);
