import { DraggableRow } from "./DraggableRow"
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DraggableRow,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=21288-130668&m=dev",
  {
    props: {
      showLeftControls: figma.boolean("Show Left Controls"),
      showActions: figma.boolean("Show actions"),
      size: figma.enum("Size", {
        Default: "default",
        Compact: "compact",
      }),
      state: figma.enum("State", {
        Default: "default",
        "On Drag": "on-drag",
        "Drag Outside": "drag-outside",
      }),
      selected: figma.boolean("Selected"),
      bordered: figma.boolean("Bordered"),
    },
    example: (props) => <DraggableRow />,
  },
)
