import React from "react"
import { MenuItem } from "./MenuItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MenuItem,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2579-17546&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showLeadingIcon: figma.boolean("Show Leading Icon"),
      showDescr: figma.boolean("Show Descr. "),
      descrText: figma.string("Descr. Text"),
      showActionIcon: figma.boolean("Show action icon"),
      menuItemText: figma.string("Menu item Text"),
      menuItem: figma.enum("Menu Item", {
        Basic: "basic",
        "Checkbox select": "checkbox-select",
        "Option Select": "option-select",
        Danger: "danger",
        "With external link on hover": "with-external-link-on-hover",
        "Drill Down - Breadcrumb": "drill-down---breadcrumb",
        "Drill Down - Start": "drill-down---start",
        "Drill Down - Return": "drill-down---return",
        "Group Header": "group-header",
        Separator: "separator",
        Footer: "footer",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Selected: "selected",
        Disabled: "disabled",
      }),
    },
    example: (props) => <MenuItem />,
  },
)
