import React from "react"
import { ProgressBar } from "./ProgressBar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ProgressBar,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=7644-38395&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      title: figma.string("Title"),
      showMainPercentage: figma.boolean("Show main percentage"),
      showOutsidePercentage: figma.boolean("Show outside percentage"),
      showMainIcon: figma.boolean("Show main icon"),
      showInsidePercentage: figma.boolean("Show inside percentage"),
      showHelperText: figma.boolean("Show helper text"),
      size: figma.enum("Size", {
        Default: "default",
        Small: "small",
        Large: "large",
      }),
      state: figma.enum("State", {
        Default: "default",
        Success: "success",
        Warning: "warning",
        Error: "error",
      }),
    },
    example: (props) => <ProgressBar />,
  },
)
