import React from "react"
import { LabelInGroup } from "./LabelInGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  LabelInGroup,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2800-1067&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      countText: figma.string("Count text"),
      hasCloseButton: figma.boolean("Has Close button"),
      hasCounter: figma.boolean("Has counter"),
      labelText: figma.string("Label text"),
    },
    example: (props) => <LabelInGroup />,
  },
)
