import React from "react"
import { LabelNonStatus } from "./LabelNonStatus"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  LabelNonStatus,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2800-609&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      hasIcon: figma.boolean("Has icon"),
      isEditable: figma.boolean("Is Editable"),
      text: figma.string("Text"),
      dismissable: figma.boolean("Dismissable"),
      color: figma.enum("Color", {
        Red: "red",
        Orange: "orange",
        "Orange Red": "orange-red",
        Gold: "gold",
        Green: "green",
        Cyan: "cyan",
        Blue: "blue",
        Purple: "purple",
        Grey: "grey",
      }),
      type: figma.enum("Type", {
        Filled: "filled",
        Outlined: "outlined",
      }),
      size: figma.enum("Size", {
        Default: "default",
        Compact: "compact",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
      }),
    },
    example: (props) => <LabelNonStatus />,
  },
)
