import { Badge } from 'src/components/Badge';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=1259-1132&m=dev',
  {
    props: {
      text: figma.string('Text'),
      // because type is an enum, disabled, read, etc are booleans needed for react component
      isDisabled: figma.enum('Type', { disabled: true }),
      isRead: figma.enum('Type', { Read: true }),
      screenReaderText: 'Badge',
      children: ''
    },
    example: (props) => (
      <Badge
        isDisabled={props.isRead ? undefined : props.isDisabled}
        isRead={props.isDisabled ? undefined : props.isRead}
      >
        {props.text}
      </Badge>
    )
  }
);
