import figma from '@figma/code-connect';
import { NavExpandable, NavItem } from '@patternfly/react-core';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  NavExpandable,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2104-7117',
  {
    props: {
      headerTitle: figma.string('✏️ Header title'),
      children: figma.children('*')
    },
    example: (props) => (
      <NavExpandable title={props.headerTitle}>
        <NavItem>{props.children}</NavItem>
      </NavExpandable>
    )
  }
);
