import React from 'react';
import { BaseComponentsToggleGroupsParts } from './BaseComponentsToggleGroupsParts';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BaseComponentsToggleGroupsParts,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2089-5606&m=dev',
  {
    props: {
      hasText: figma.boolean('Has text'),
      hasIcon: figma.boolean('Has icon'),
      text: figma.string('Text'),
      position: figma.enum('Position', {
        Left: 'left',
        Middle: 'middle',
        RIght: 'right'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected',
        Disabled: 'disabled'
      }),
      size: figma.enum('Size', {
        Default: 'default',
        Compact: 'compact'
      })
    },
    example: (props) => <BaseComponentsToggleGroupsParts />
  }
);
