import figma from '@figma/code-connect';
import { PageTextSectionDefault } from '@patternfly/react-core';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  PageTextSectionDefault,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2104-8581&t=IzSunfrnw18ti37Y-11',
  {
    props: {
      showButton: figma.boolean('Show button'),
      title: figma.string('✏️ Title'),
      showLogoDivider: figma.boolean('Show logo + divider'),
      showInlineLink: figma.boolean('Show inline link'),
      showActionsMenu: figma.boolean('Show actions menu'),
      showLabel: figma.boolean('Show label'),
      description: figma.string('✏️ Description'),
      showPageDescription: figma.boolean('Show page description'),
      showPageTitle: figma.boolean('Show page title')
    },
    example: (props) => (
      // Documentation for PageTextSectionDefault can be found at https://www.patternfly.org/components/page
      <PageTextSectionDefault />
    )
  }
);
