import { PageContentArea } from './PageContentArea';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  PageContentArea,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=25656-311374&t=IzSunfrnw18ti37Y-11',
  {
    props: {
      type: figma.enum('Type', {
        Primary: 'primary',
        Mixed: 'mixed',
        'All secondary': 'all-secondary',
        DIY: 'diy'
      })
    },
    example: (props) => (
      // Documentation for PageContentArea can be found at https://www.patternfly.org/components/page
      <PageContentArea />
    )
  }
);
