import { TopPageSection } from "./TopPageSection"
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TopPageSection,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2104-8584&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showBreadcrumbs: figma.boolean("Show breadcrumbs"),
      showSubNav: figma.boolean("Show sub nav"),
      type: figma.enum("Type", {
        Breadcrumbs: "breadcrumbs",
        Empty: "empty",
        "In-Page Horizontal Nav": "in-page-horizontal-nav",
      }),
    },
    example: (props) => <TopPageSection />,
  },
)
