import React from "react"
import { MultipleFileUpload } from "./MultipleFileUpload"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MultipleFileUpload,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=8949-96128&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      layout: figma.enum("Layout", {
        Default: "default",
        Horizontal: "horizontal",
      }),
      state: figma.enum("State", {
        Default: "default",
        "Drag over": "drag-over",
        "Uploading + Collapsed": "uploading---collapsed",
        "Uploaded + Collapsed": "uploaded---collapsed",
        "Failed upload + Collapsed": "failed-upload---collapsed",
        "Uploading + Expanded": "uploading---expanded",
        "Uploaded + Expanded": "uploaded---expanded",
        "Failed Upload + Expanded": "failed-upload---expanded",
      }),
    },
    example: (props) => <MultipleFileUpload />,
  },
)
