import React from "react"
import { MultipleFileUploadDragArea } from "./MultipleFileUploadDragArea"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MultipleFileUploadDragArea,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=8949-96079&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      state: figma.enum("State", {
        Default: "default",
        "Drag Over": "drag-over",
      }),
      layout: figma.enum("Layout", {
        Basic: "basic",
        Horizontal: "horizontal",
      }),
    },
    example: (props) => <MultipleFileUploadDragArea />,
  },
)
