import figma from '@figma/code-connect';
import { SearchInput } from '@patternfly/react-core';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SearchInput,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=8065-140343&t=IzSunfrnw18ti37Y-11',
  {
    props: {},
    example: (props) => (
      // Documentation for SearchInput can be found at https://www.patternfly.org/components/search-input
      <SearchInput />
    )
  }
);
