import React from "react"
import { NotificationDrawerItem } from "./NotificationDrawerItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  NotificationDrawerItem,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=3164-16861&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      status: figma.enum("Status", {
        Danger: "danger",
        Info: "info",
        Success: "success",
        Warning: "warning",
      }),
      type: figma.enum("Type", {
        Unread: "unread",
        Read: "read",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
      }),
      topActionType: figma.enum("Top Action Type", {
        "Icon button": "icon-button",
        "Link button": "link-button",
      }),
    },
    example: (props) => <NotificationDrawerItem />,
  },
)
