import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1259-678&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      iconLeft: figma.boolean("Icon left"),
      showCount: figma.boolean("Show Count"),
      iconRight: figma.boolean("Icon right"),
      text: figma.string("✏️ Text"),
      type: figma.enum("Type", {
        Primary: "primary",
        Secondary: "secondary",
        Tertiary: "tertiary",
        Danger: "danger",
        "Secondary Danger": "secondary-danger",
        Warning: "warning",
        Progress: "progress",
        "Secondary Progress": "secondary-progress",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Clicked: "clicked",
        Disabled: "disabled",
      }),
      size: figma.enum("Size", {
        Default: "default",
        Small: "small",
      }),
    },
    example: (props) => <Button />,
  },
)
