import React from "react"
import { IconButtonPlainButton } from "./IconButtonPlainButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  IconButtonPlainButton,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1259-736&t=TMTA4Fpy1ljK4qQP-11",
  {
    props: {
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Clicked: "clicked",
        Disabled: "disabled",
      }),
      type: figma.enum("Type", {
        "Default (with padding)": "default--with-padding-",
        "No padding": "no-padding",
      }),
    },
    example: (props) => <IconButtonPlainButton />,
  },
)
