import React from "react"
import { InlineLink } from "./InlineLink"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  InlineLink,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1291-2153&t=TMTA4Fpy1ljK4qQP-11",
  {
    props: {
      text: figma.string("Text"),
      type: figma.enum("Type", {
        Default: "default",
        "Inline link external": "inline-link-external",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Disabled: "disabled",
        Visited: "visited",
      }),
    },
    example: (props) => <InlineLink />,
  },
)
