import React from "react"
import { LinkButton } from "./LinkButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  LinkButton,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1259-745&t=TMTA4Fpy1ljK4qQP-11",
  {
    props: {
      text: figma.string("✏️ Text"),
      text: figma.string("Text"),
      iconLeft: figma.boolean("Icon left"),
      iconRight: figma.boolean("Icon right"),
      type: figma.enum("Type", {
        Default: "default",
        Danger: "danger",
        "External link": "external-link",
        "Button with count": "button-with-count",
        Progress: "progress",
      }),
      state: figma.enum("State", {
        Default: "default",
        Disabled: "disabled",
        Hover: "hover",
        Clicked: "clicked",
      }),
      size: figma.enum("Size", {
        Default: "default",
        Small: "small",
      }),
    },
    example: (props) => <LinkButton />,
  },
)
