import React from "react"
import { SplitButtonComponents } from "./SplitButtonComponents"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SplitButtonComponents,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=3102-7154&t=TMTA4Fpy1ljK4qQP-11",
  {
    props: {
      text: figma.string("Text"),
      leftOrRight: figma.enum("Left or Right", {
        Left: "left",
        Right: "right",
      }),
      type: figma.enum("Type", {
        Primary: "primary",
        Secondary: "secondary",
        Tertiary: "tertiary",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Disabled: "disabled",
        Clicked: "clicked",
      }),
    },
    example: (props) => <SplitButtonComponents />,
  },
)
