import React from "react"
import { StatefulButton } from "./StatefulButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  StatefulButton,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=5805-20130&t=TMTA4Fpy1ljK4qQP-11",
  {
    props: {
      text: figma.string("Text ✏️"),
      showText: figma.boolean("Show text"),
      showIcon: figma.boolean("Show Icon"),
      type: figma.enum("Type", {
        Read: "read",
        Unread: "unread",
        "Unread - Needs attention": "unread---needs-attention",
      }),
      state: figma.enum("State", {
        "Closed (default)": "closed--default-",
        Hover: "hover",
        Expanded: "expanded",
      }),
    },
    example: (props) => <StatefulButton />,
  },
)
