import { DualListItemBaseComponent } from '@patternfly/react-core';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 */

figma.connect(
  DualListItemBaseComponent,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=21279-116294&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      itemText: figma.string("Item text"),
      hasCounter: figma.boolean("Has counter"),
      checkbox: figma.boolean("Checkbox"),
      expandable: figma.boolean("Expandable"),
      isDraggable: figma.boolean("Is Draggable"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Selected: "selected",
        "On Drag": "on-drag",
        "Drag Outside": "drag-outside",
      }),
    },
    example: (props) => <DualListItemBaseComponent />,
  },
)
