import { DualListItemTree } from '@patternfly/react-core';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 */

figma.connect(
  DualListItemTree,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=21279-116342&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      type: figma.enum("Type", {
        Default: "default",
        "Select all": "select-all",
        "Select mix": "select-mix",
        "Sub items - tertiary": "sub-items---tertiary",
      }),
    },
    example: (props) => <DualListItemTree />,
  },
)
