import React from "react"
import { Checkbox } from "./Checkbox"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=157-3078&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      description: figma.string("✏️ Description"),
      description: figma.boolean("Description"),
      toggleLabel: figma.string("✏️ Toggle label"),
      type: figma.enum("Type", {
        "With Label": "with-label",
        Standalone: "standalone",
      }),
      state: figma.enum("State", {
        Default: "default",
        Disabled: "disabled",
      }),
      labelPlacement: figma.enum("Label placement", {
        Default: "default",
        Reversed: "reversed",
      }),
    },
    example: (props) => <Checkbox />,
  },
)
