import React from "react"
import { FieldGroupHeader } from "./FieldGroupHeader"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FieldGroupHeader,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=17114-21473&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showAction: figma.boolean("Show action"),
      showDescription: figma.boolean("Show description"),
      type: figma.enum("Type", {
        "expandable - open": "expandable---open",
        "non - expandable": "non---expandable",
        "expandable - closed": "expandable---closed",
      }),
      isFirstItem: figma.boolean("is first item"),
    },
    example: (props) => <FieldGroupHeader />,
  },
)
