import React from "react"
import { FieldGroup } from "./FieldGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FieldGroup,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=17114-21566&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      nestedNonExpandable: figma.boolean("nested - non expandable"),
      nestedClosed: figma.boolean("nested - closed"),
      nestedOpen: figma.boolean("nested - open"),
      type: figma.enum("Type", {
        "expandable - open": "expandable---open",
        "expandable - closed": "expandable---closed",
        "non - expandable": "non---expandable",
      }),
    },
    example: (props) => <FieldGroup />,
  },
)
