import React from "react"
import { NumberInputField } from "./NumberInputField"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  NumberInputField,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=176-3706&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      rightUnit: figma.boolean("Right unit"),
      leftUnit: figma.boolean("Left unit"),
      unit: figma.string("Unit"),
      type: figma.enum("Type", {
        Default: "default",
        "With Unit": "with-unit",
      }),
      status: figma.enum("Status", {
        Default: "default",
        Warning: "warning",
        Error: "error",
        Success: "success",
        Disabled: "disabled",
      }),
    },
    example: (props) => <NumberInputField />,
  },
)
