import React from "react"
import { RadioButton } from "./RadioButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RadioButton,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=157-2778&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      state: figma.enum("State", {
        Unchecked: "unchecked",
        Checked: "checked",
        Disabled: "disabled",
        "Checked Disabled": "checked-disabled",
      }),
    },
    example: (props) => <RadioButton />,
  },
)
