import React from "react"
import { Switches } from "./Switches"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Switches,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=157-2878&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showCheck: figma.boolean("Show check"),
      state: figma.enum("State", {
        On: "on",
        Off: "off",
        "Disabled On": "disabled-on",
        "Disabled Off": "disabled-off",
      }),
    },
    example: (props) => <Switches />,
  },
)
