import React from "react"
import { WizardStepItem } from "./WizardStepItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  WizardStepItem,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=14628-17356&m=dev",
  {
    props: {
      expandable: figma.boolean("Expandable"),
      navItem: figma.string("✏️ Nav item"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Selected: "selected",
        Disabled: "disabled",
      }),
      expansion: figma.enum("Expansion", {
        "No expansion": "no-expansion",
        "Expandable - Open": "expandable---open",
        "Expandable - closed": "expandable---closed",
      }),
    },
    example: (props) => <WizardStepItem />,
  },
)
