import React from "react"
import { WizardBasicModal } from "./WizardBasicModal"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  WizardBasicModal,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=14628-18627&m=dev",
  {
    props: {
      wizardStepTitle: figma.string("Wizard Step Title"),
      wizardStepContent: figma.string("Wizard Step Content"),
      type: figma.enum("Type", {
        "With Form": "with-form",
        Empty: "empty",
      }),
      withDrawer: figma.boolean("With drawer"),
    },
    example: (props) => <WizardBasicModal />,
  },
)
