import React from "react"
import { WizardInPage } from "./WizardInPage"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  WizardInPage,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=14628-23799&m=dev",
  {
    props: {
      wizardDescription: figma.string("Wizard Description"),
      wizardStepTitle: figma.string("Wizard Step Title"),
      wizardStepContent: figma.string("Wizard Step Content"),
      type: figma.enum("Type", {
        "In Page Empty": "in-page-empty",
        "With Drawer": "with-drawer",
        "In Page": "in-page",
      }),
      withDrawer: figma.boolean("With drawer"),
    },
    example: (props) => <WizardInPage />,
  },
)
