import React from "react"
import { WizardHeader } from "./WizardHeader"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  WizardHeader,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=14628-17329&m=dev",
  {
    props: {
      description: figma.string("✏️ Description"),
      wizardTitle: figma.string("✏️Wizard Title"),
    },
    example: (props) => <WizardHeader />,
  },
)
