import React from "react"
import { OverflowFooter } from "./OverflowFooter"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  OverflowFooter,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1110-2784&m=dev",
  {
    props: {
      text: figma.string("✏️ Text"),
      state: figma.enum("State", {
        hover: "hover",
        default: "default",
      }),
      theme: figma.enum("Theme", {
        light: "light",
      }),
    },
    example: (props) => <OverflowFooter />,
  },
)
