import React from "react"
import { ToastAlertGroup } from "./ToastAlertGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ToastAlertGroup,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1110-2821&m=dev",
  {
    props: {
      overflow: figma.boolean("Overflow"),
      property1: figma.enum("Property 1", {
        Default: "default",
      }),
    },
    example: (props) => <ToastAlertGroup />,
  },
)
