import React from "react"
import { ToastAlert } from "./ToastAlert"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ToastAlert,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1110-2587&m=dev",
  {
    props: {
      description: figma.boolean("Description"),
      description: figma.string("✏️ Description"),
      title: figma.string("✏️ Title"),
      actions: figma.boolean("Actions"),
      expandable: figma.boolean("Expandable"),
      type: figma.enum("Type", {
        Info: "info",
        Success: "success",
        Warning: "warning",
        Danger: "danger",
        Custom: "custom",
      }),
    },
    example: (props) => <ToastAlert />,
  },
)
