// import React from "react"
// import { FieldGroupHeaderNested } from "./FieldGroupHeaderNested"
// import figma from '@figma/code-connect'

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   FieldGroupHeaderNested,
//   "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=17114-21536&t=IzSunfrnw18ti37Y-11",
//   {
//     props: {
//       showDescription: figma.boolean("Show description"),
//       type: figma.enum("Type", {
//         "expandable - closed": "expandable---closed",
//         "expandable - open": "expandable---open",
//         "non - expandable": "non---expandable",
//       }),
//     },
//     example: (props) => (
//       // Documentation for FieldGroupHeaderNested can be found at https://www.patternfly.org/components/form-field-group
//       <FieldGroupHeaderNested />
//     ),
//   },
// )
