// import React from "react"
// import { LabeledInputGroup } from "./LabeledInputGroup"
// import figma from '@figma/code-connect'

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   LabeledInputGroup,
//   "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=176-3526&t=IzSunfrnw18ti37Y-11",
//   {
//     props: {
//       helperText: figma.boolean("Helper text"),
//       label: figma.boolean("Label"),
//     },
//     example: (props) => (
//       // Documentation for LabeledInputGroup can be found at https://www.patternfly.org/components/labeled-input-group
//       <LabeledInputGroup />
//     )
//   }
// );
