// import React from "react"
// import { SimpleFileUpload } from "./SimpleFileUpload"
// import figma from '@figma/code-connect'

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   SimpleFileUpload,
//   "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=8949-96043&t=IzSunfrnw18ti37Y-11",
//   {
//     props: {
//       showTextPreviewBox: figma.boolean("Show text preview box"),
//       showHelperText: figma.boolean("Show helper text"),
//       state: figma.enum("State", {
//         Default: "default",
//         "Invalid upload": "invalid-upload",
//         "Drag state": "drag-state",
//         "In progress upload": "in-progress-upload",
//         "Uploaded + Not editable": "uploaded---not-editable",
//         "Uploaded + Editable": "uploaded---editable",
//       }),
//     },
//     example: (props) => (
//       // Documentation for SimpleFileUpload can be found at https://www.patternfly.org/components/simple-file-upload
//       <SimpleFileUpload />
//     )
//   }
// );
