// import React from "react"
// import { Switch } from "./Switch"
// import figma from '@figma/code-connect'

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   Switch,
//   "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=157-3431&t=IzSunfrnw18ti37Y-11",
//   {
//     props: {
//       toggleLabel: figma.string("✏️ Toggle label"),
//       type: figma.enum("Type", {
//         "With Label": "with-label",
//         Standalone: "standalone",
//       }),
//       state: figma.enum("State", {
//         Disabled: "disabled",
//         Off: "off",
//         On: "on",
//         Default: "default",
//       }),
//       labelPlacement: figma.enum("Label placement", {
//         Default: "default",
//         Reversed: "reversed",
//       }),
//     },
//     example: (props) => (
//       // Documentation for Switch can be found at https://www.patternfly.org/components/switch
//       <Switch />
//     )
//   }
// );
