import React from "react"
import { Drawer } from "./Drawer"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Drawer,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=8034-7676&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showFooterActions: figma.boolean("Show Footer actions"),
      hasDescription: figma.boolean("Has description"),
      headerText: figma.string("Header text"),
      isResizable: figma.boolean("Is resizable"),
      description: figma.string("Description"),
      hasTabs: figma.boolean("Has tabs"),
      hasActionIcon: figma.boolean("Has action icon"),
      position: figma.enum("Position", {
        "Left - In Main Content Area": "left---in-main-content-area",
        "Right - Full page": "right---full-page",
        "Left - Full Page": "left---full-page",
        "Bottom - Full page": "bottom---full-page",
        "Bottom - In Main Content Area": "bottom---in-main-content-area",
        "Right - In Main Content Area": "right---in-main-content-area",
      }),
      background: figma.enum("Background", {
        Default: "default",
        Secondary: "secondary",
      }),
      type: figma.enum("Type", {
        Overlay: "overlay",
        Inline: "inline",
      }),
    },
    example: (props) => <Drawer />,
  },
)
