import React from "react"
import { DrawerMain } from "./DrawerMain"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DrawerMain,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=35586-211216&m=dev",
  {
    props: {
      header: figma.boolean("Header"),
      headerText: figma.string("* Header text"),
      position: figma.enum("Position", {
        Default: "default",
        Left: "left",
      }),
    },
    example: (props) => <DrawerMain />,
  },
)
