import React from "react"
import { BasicSearchInput } from "./BasicSearchInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BasicSearchInput,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=8065-140137&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      searchedText: figma.string("✏️ Searched text"),
      showCloseButton: figma.boolean("Show close button"),
      showNavigableOptions: figma.boolean("Show navigable options"),
      placeholderText: figma.string("✏️ Placeholder text"),
      showCount: figma.boolean("Show count"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Clicked: "clicked",
        Filled: "filled",
        "Filled - Hover": "filled---hover",
        "Filled - Clicked": "filled---clicked",
      }),
      showSubmitButton: figma.boolean("Show submit button"),
    },
    example: (props) => <BasicSearchInput />,
  },
)
