import figma from '@figma/code-connect';
import { BreadcrumbItem } from '@patternfly/react-core';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BreadcrumbItem,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=3362-74&t=TMTA4Fpy1ljK4qQP-11',
  {
    props: {
      // strings
      text: figma.string('Text'),

      // enums
      type: figma.enum('Type', {
        Home: 'home',
        'Breadcrumb item': 'breadcrumb-item'
      }),
      state: figma.enum('State', {
        Link: 'link',
        Hover: undefined,
        'No link': 'no-link'
      })
    },
    example: (props) => <BreadcrumbItem text={props.text} type={props.type} state={props.state} />
  }
);
