import figma from '@figma/code-connect';
import { Breadcrumbs } from '@patternfly/react-core';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Breadcrumbs,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=3362-283&m=dev',
  {
    props: {
      // enums
      type: figma.enum('Type', {
        'No home link': 'no-home-link',
        'No home link collapsed': 'no-home-link-collapsed',
        'Home link': 'home-link',
        'Home link collapsed': 'home-link-collapsed'
      }),
      children: figma.children('*')
    },
    example: (props) =>
      <Breadcrumbs type={props.type}>
        {props.children}
      </Breadcrumbs>
  }
);
