import React from "react"
import { SimpleListItems } from "./SimpleListItems"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SimpleListItems,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=4410-20664&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      text: figma.string("Text"),
      state: figma.enum("State", {
        Default: "default",
        "Hover - Light": "hover---light",
        "Hover - Dark": "hover---dark",
        "Selected - Light": "selected---light",
        "Selected - Dark": "selected---dark",
        Disabled: "disabled",
      }),
      type: figma.enum("Type", {
        Default: "default",
        Link: "link",
      }),
    },
    example: (props) => <SimpleListItems />,
  },
)
