import React from "react"
import { ProgressStepperIcons } from "./ProgressStepperIcons"
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ProgressStepperIcons,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=7644-38703&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      state: figma.enum("State", {
        Pending: "pending",
        Warning: "warning",
        "Loading/Misc State": "loading-misc-state",
        Failure: "failure",
        Success: "success",
        "In Progress": "in-progress",
      }),
      size: figma.enum("Size", {
        Default: "default",
        Compact: "compact",
      }),
    },
    example: (props) => <ProgressStepperIcons />,
  },
)
