import React from "react"
import { ProgressStepperLine } from "./ProgressStepperLine"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ProgressStepperLine,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=7644-38613&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      direction: figma.enum("Direction", {
        Horizontal: "horizontal",
        Vertical: "vertical",
      }),
    },
    example: (props) => <ProgressStepperLine />,
  },
)
