import React from "react"
import { Tooltip } from "./Tooltip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=6598-70985&m=dev",
  {
    props: {
      text: figma.string("Text"),
      type: figma.enum("Type", {
        "Top-right": "top-right",
        "Bottom-right": "bottom-right",
        "Left-bottom": "left-bottom",
        "Right-bottom": "right-bottom",
        "Top-left": "top-left",
        "Top-middle": "top-middle",
        "Bottom-left": "bottom-left",
        "Bottom-middle": "bottom-middle",
        "Left-top": "left-top",
        "Left-middle": "left-middle",
        "Right-top": "right-top",
        "Right-middle": "right-middle",
      }),
    },
    example: (props) => <Tooltip />,
  },
)
