import { NotificationDrawerHeader } from './NotificationDrawerHeader';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  NotificationDrawerHeader,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=3170-17841&t=IzSunfrnw18ti37Y-11',
  {
    props: {
      showUnreadCount: figma.boolean('Show unread count'),
      unreadCount: figma.string('Unread count'),
      headingText: figma.string('Heading text'),
      hasActionsMenu: figma.boolean('Has actions menu')
    },
    example: (props) => (
      // Documentation for NotificationDrawerHeader can be found at https://www.patternfly.org/components/notification-drawer
      <NotificationDrawerHeader />
    )
  }
);
