import React from "react"
import { SliderThumb } from "./SliderThumb"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SliderThumb,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2698-49&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showThumbInput: figma.boolean("Show thumb input"),
      number: figma.string("✏️ Number"),
      show: figma.boolean("Show "),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Disabled: "disabled",
        Active: "active",
      }),
    },
    example: (props) => <SliderThumb />,
  },
)
