import React from "react"
import { FieldSpecificInlineEdit } from "./FieldSpecificInlineEdit"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FieldSpecificInlineEdit,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1664-8856&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showTermLabel: figma.boolean("Show term label"),
      state: figma.enum("State", {
        "Read only view": "read-only-view",
        "Edit view": "edit-view",
      }),
    },
    example: (props) => <FieldSpecificInlineEdit />,
  },
)
