import React from "react"
import { InlineEditActionGroup } from "./InlineEditActionGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  InlineEditActionGroup,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1664-5805&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      type: figma.enum("Type", {
        Icons: "icons",
        Buttons: "buttons",
      }),
      state: figma.enum("State", {
        Default: "default",
        Invalid: "invalid",
      }),
    },
    example: (props) => <InlineEditActionGroup />,
  },
)
