import { ProgressSteps } from './ProgressSteps';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ProgressSteps,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=7644-38618&t=IzSunfrnw18ti37Y-11',
  {
    props: {
      popoverUnderline: figma.boolean('Popover Underline '),
      description: figma.boolean('Description'),
      state: figma.enum('State', {
        'In progress status': 'in-progress-status',
        'Pending status': 'pending-status',
        'Failure status': 'failure-status',
        'Completed status': 'completed-status',
        'Warning status': 'warning-status',
        'Loading/Misc. state': 'loading-misc--state'
      }),
      direction: figma.enum('Direction', {
        Horizontal: 'horizontal',
        Vertical: 'vertical'
      })
    },
    example: (props) => (
      // Documentation for ProgressSteps can be found at https://www.patternfly.org/components/progress-stepper
      <ProgressSteps />
    )
  }
);
