import React from "react"
import { ExandableSectionTruncate } from "./ExandableSectionTruncate"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ExandableSectionTruncate,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2769-146&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      expandedTruncateText: figma.string("Expanded Truncate Text"),
      toggleTextLess: figma.string("Toggle Text Less"),
      defaultTruncateText: figma.string("Default Truncate Text"),
      toggleTextMore: figma.string("Toggle Text More"),
      state: figma.enum("State", {
        Default: "default",
        Expanded: "expanded",
      }),
    },
    example: (props) => <ExandableSectionTruncate />,
  },
)
