import React from "react"
import { ExpandableSectionDisclosure } from "./ExpandableSectionDisclosure"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ExpandableSectionDisclosure,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2810-80&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      toggleTextLess: figma.string("Toggle Text Less"),
      toggleTextMore: figma.string("Toggle Text More"),
      expandedText: figma.string("Expanded Text"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Expanded: "expanded",
        "Expand Uncontrolled": "expand-uncontrolled",
        "Expanded Indent": "expanded-indent",
        "Default Custom Content": "default-custom-content",
        "Expanded Custom Content": "expanded-custom-content",
      }),
    },
    example: (props) => <ExpandableSectionDisclosure />,
  },
)
