import React from "react"
import { DesktopPageWithLeftNav } from "./DesktopPageWithLeftNav"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DesktopPageWithLeftNav,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=3864-23403&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      contentAreaPresets: figma.instance("Content Area Presets"),
      sideNav: figma.enum("Side nav", {
        Open: "open",
        Closed: "closed",
      }),
    },
    example: (props) => <DesktopPageWithLeftNav />,
  },
)
