import React from "react"
import { PrimaryDetail } from "./PrimaryDetail"
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  PrimaryDetail,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=25656-311494&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      type: figma.enum("type", {
        "simple list": "simple-list",
        "with drawer": "with-drawer",
        "with inline drawer": "with-inline-drawer",
        "data list": "data-list",
      }),
    },
    example: (props) => <PrimaryDetail />,
  },
)
