import React from "react"
import { JumplinkHorizontal } from "./JumplinkHorizontal"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  JumplinkHorizontal,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=5286-5330&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      closeIcon: figma.boolean("Close Icon"),
      helpIcon: figma.boolean("Help icon"),
      hasIcon: figma.boolean("Has icon"),
      tabText: figma.string("Tab Text"),
      state: figma.enum("State", {
        Default: "default",
        Selected: "selected",
        Hover: "hover",
      }),
    },
    example: (props) => <JumplinkHorizontal />,
  },
)
