import React from "react"
import { TreeView } from "./TreeView"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TreeView,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=12615-2825&m=dev",
  {
    props: {
      withSearch: figma.boolean("With Search"),
      type: figma.enum("Type", {
        Default: "default",
        "separate selection & expansion": "separate-selection---expansion",
        "With Branching": "with-branching",
        "With Checkboxes": "with-checkboxes",
        "With Icons": "with-icons",
        "With Badges": "with-badges",
        "With Actions": "with-actions",
      }),
    },
    example: (props) => <TreeView />,
  },
)
