import React from "react"
import { TreeViewCompactNode } from "./TreeViewCompactNode"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TreeViewCompactNode,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=12615-3292&m=dev",
  {
    props: {
      lvl4Indent: figma.boolean("Lvl4 Indent"),
      lvl2Indent: figma.boolean("Lvl2 Indent"),
      lvl3Indent: figma.boolean("Lvl3 Indent"),
      lvl1Indent: figma.boolean("Lvl1 Indent"),
      type: figma.enum("Type", {
        Default: "default",
        "Caret Collapsed": "caret-collapsed",
        "Caret Expanded": "caret-expanded",
        "Bgrd w Guide": "bgrd-w-guide",
        "Bgrd w End Guide": "bgrd-w-end-guide",
        "Bgrd w End Guide Expanded": "bgrd-w-end-guide-expanded",
        "Bgrd w End Guide Collapsed": "bgrd-w-end-guide-collapsed",
        "Bgrd w Guide Expanded": "bgrd-w-guide-expanded",
        "Bgrd w Guide Collapsed": "bgrd-w-guide-collapsed",
        Spacer: "spacer",
        "No Bgrd w Guide": "no-bgrd-w-guide",
        "No Bgrd w End Guide": "no-bgrd-w-end-guide",
        "No Bgrd w End Guide Expanded": "no-bgrd-w-end-guide-expanded",
        "No Bgrd w End Guide Collapsed": "no-bgrd-w-end-guide-collapsed",
        "No Bgrd w Guide Expanded": "no-bgrd-w-guide-expanded",
        "No Bgrd w Guide Collapsed": "no-bgrd-w-guide-collapsed",
      }),
    },
    example: (props) => <TreeViewCompactNode />,
  },
)
