import React from "react"
import { TreeViewNode } from "./TreeViewNode"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TreeViewNode,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=12615-3260&m=dev",
  {
    props: {
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Selected: "selected",
        "Expanded - Not Selected": "expanded---not-selected",
      }),
      expandable: figma.boolean("Expandable"),
    },
    example: (props) => <TreeViewNode />,
  },
)
