import React from "react"
import { TreeNodeBaseComponent } from "./TreeNodeBaseComponent"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TreeNodeBaseComponent,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=12615-3269&m=dev",
  {
    props: {
      withCheckbox: figma.boolean("With Checkbox"),
      noCaretIndent: figma.boolean("No Caret Indent"),
      showCaret: figma.boolean("Show Caret"),
      lvl3Indent: figma.boolean("Lvl 3 Indent"),
      text: figma.string("Text"),
      withActions: figma.boolean("With Actions"),
      defaultText: figma.boolean("Default Text"),
      lvl2Indent: figma.boolean("Lvl 2 Indent"),
      nodeGuide: figma.boolean("Node Guide"),
      lvl4Indent: figma.boolean("Lvl 4 Indent"),
      withIcon: figma.boolean("With Icon"),
      sepSelectionText: figma.boolean("Sep. Selection Text"),
      lvl1Indent: figma.boolean("Lvl 1 Indent"),
      endNodeGuide: figma.boolean("End Node Guide"),
      showBadge: figma.boolean("Show Badge"),
    },
    example: (props) => <TreeNodeBaseComponent />,
  },
)
