import React from "react"
import { BasicRow } from "./BasicRow"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BasicRow,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2930-36939&m=dev",
  {
    props: {
      showLeftControls: figma.boolean("Show Left Controls"),
      showRightActions: figma.boolean("Show Right actions"),
      expanded: figma.boolean("Expanded"),
      selected: figma.boolean("Selected"),
      bordered: figma.boolean("Bordered"),
      size: figma.enum("Size", {
        Default: "default",
        Compact: "compact",
      }),
      rowStripe: figma.boolean("Row stripe"),
    },
    example: (props) => <BasicRow />,
  },
)
