import React from "react"
import { ColumnHeaderLeftControls } from "./ColumnHeaderLeftControls"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ColumnHeaderLeftControls,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=6241-29618&m=dev",
  {
    props: {
      isDraggable: figma.boolean("Is draggable"),
      expandableAll: figma.boolean("Expandable all"),
      selectAll: figma.boolean("Select all"),
      size: figma.enum("Size", {
        Default: "default",
        Compact: "compact",
      }),
    },
    example: (props) => <ColumnHeaderLeftControls />,
  },
)
