import React from "react"
import { ColumnHeaderHeaderCell } from "./ColumnHeaderHeaderCell"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ColumnHeaderHeaderCell,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=14-623&m=dev",
  {
    props: {
      showHelpIcon: figma.boolean("Show help icon"),
      sortable: figma.boolean("Sortable"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Empty: "empty",
        "Sorted - Ascending": "sorted---ascending",
        "Sorted - Descending": "sorted---descending",
      }),
      size: figma.enum("Size", {
        Compact: "compact",
        Default: "default",
      }),
    },
    example: (props) => <ColumnHeaderHeaderCell />,
  },
)
