import React from "react"
import { CompoundExpandableRows } from "./CompoundExpandableRows"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CompoundExpandableRows,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2945-48504&m=dev",
  {
    props: {
      showActions: figma.boolean("Show actions"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
      }),
      expanded: figma.boolean("Expanded"),
      selected: figma.enum("Selected", {
        False: "false",
      }),
    },
    example: (props) => <CompoundExpandableRows />,
  },
)
