import React from "react"
import { RowBasedTableRecommended } from "./RowBasedTableRecommended"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  RowBasedTableRecommended,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=3331-12049&m=dev",
  {
    props: {
      type: figma.enum("Type", {
        "Basic Table": "basic-table",
        "Selectable Table": "selectable-table",
        "Clickable & Selectable table": "clickable---selectable-table",
      }),
      size: figma.enum("Size", {
        Compact: "compact",
        Default: "default",
      }),
      bordered: figma.boolean("Bordered"),
      expandable: figma.boolean("Expandable"),
    },
    example: (props) => <RowBasedTableRecommended />,
  },
)
