import React from "react"
import { TableCellDefaultContentCell } from "./TableCellDefaultContentCell"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TableCellDefaultContentCell,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=14-389&m=dev",
  {
    props: {
      showSecondaryText: figma.boolean("Show secondary text"),
      labelType: figma.instance("Label type"),
      type: figma.enum("Type", {
        "Icon + Text": "icon---text",
        Link: "link",
        Text: "text",
        "Inline edit": "inline-edit",
        "Icon only": "icon-only",
        Label: "label",
        Skeleton: "skeleton",
      }),
      size: figma.enum("Size", {
        Default: "default",
        Compact: "compact",
      }),
    },
    example: (props) => <TableCellDefaultContentCell />,
  },
)
