import React from "react"
import { CardTileBaseComponent } from "./CardTileBaseComponent"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CardTileBaseComponent,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=12615-19749&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      titleText: figma.string("Title text"),
      subtitle: figma.string("Subtitle"),
      showSubtitle: figma.boolean("Show subtitle"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Clicked: "clicked",
        Disabled: "disabled",
      }),
    },
    example: (props) => <CardTileBaseComponent />,
  },
)
