import React from "react"
import { CardBackgroundsEmptyCards } from "./CardBackgroundsEmptyCards"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CardBackgroundsEmptyCards,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=21430-192144&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Clicked: "clicked",
      }),
      type: figma.enum("Type", {
        Primary: "primary",
        Secondary: "secondary",
      }),
    },
    example: (props) => <CardBackgroundsEmptyCards />,
  },
)
