import React from "react"
import { MultiselectCard } from "./MultiselectCard"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MultiselectCard,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=3144-18682&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      footerComponentSlots: figma.boolean("Footer Component Slots"),
      bodyComponentSlots: figma.boolean("Body Component Slots"),
      cardTitle: figma.string("✏️ Card title"),
      trailingTitleIcon: figma.boolean("Trailing Title Icon"),
      cardBody: figma.string("✏️ Card body"),
      cardDescription: figma.string("✏️ Card description"),
      leadingTitleIcon: figma.boolean("Leading Title Icon"),
      cardDescription: figma.boolean("Card description"),
      cardHeader: figma.boolean("Card header"),
      bodyText: figma.boolean("Body text"),
      cardBody: figma.boolean("Card body"),
      cardFooter: figma.string("✏️ Card footer"),
      expandableBody: figma.boolean("Expandable body"),
      cardFooter: figma.boolean("Card footer"),
      headerImage: figma.boolean("Header image"),
      state: figma.enum("State", {
        Default: "default",
        Disabled: "disabled",
        Hover: "hover",
        Selected: "selected",
      }),
      style: figma.enum("Style", {
        Default: "default",
        Secondary: "secondary",
      }),
      size: figma.enum("Size", {
        Compact: "compact",
        Default: "default",
        Large: "large",
      }),
      isExpandable: figma.boolean("Is expandable"),
    },
    example: (props) => <MultiselectCard />,
  },
)
