// import { Accordion } from 'src/components/Accordion';
// import { AccordionToggle } from 'src/components/Accordion/AccordionToggle.tsx';
// import figma from '@figma/code-connect';

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   Accordion,
//   'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=1423-687&t=RkT5gWMekgR8L2ew-11',
//   {
//     props: {
//       toggleTextLarge: figma.string('Toggle Text Large'),
//       toggleTextExpanded: figma.string('Toggle Text Expanded'),
//       toggleText: figma.string('Toggle Text'),
//       expandText: figma.string('Expand Text'),
//       type: figma.enum('Type', {
//         Regular: 'regular',
//         Bordered: 'bordered',
//         'Large Bordered': 'large-bordered'
//       }),
//       state: figma.enum('State', {
//         Default: 'default',
//         Hover: 'hover',
//         Expanded: 'expanded'
//       }),
//       caretPosition: figma.enum('Caret position', {
//         Right: 'right',
//         Left: 'left'
//       })
//     },
//     example: (props) => <Accordion />
//   }
// );
