import { Alert, AlertGroup, AlertDescription } from 'src/components/Alert';
import { Content, ContentVariants } from 'src/components/Content';
import figma from '@figma/code-connect';
import { group } from 'console';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

/**
 * Toast - Alert modal example
 */
figma.connect(
  Alert,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=2940-18403&t=msxik5ft6Jtj86xV-11',
  {
    props: {
      showComponentSlot: figma.boolean('Show component slot'),
      helpIcon: figma.boolean('Help icon'),
      description: figma.boolean('Description'),
      status: figma.enum('Status', {
        Success: 'success',
        Warning: 'warning',
        Danger: 'danger',
        Info: 'info',
        'Custom alert': 'custom-alert'
      }),
      size: figma.enum('Size', {
        Small: 'small',
        Medium: 'medium',
        Large: 'large'
      })
    },
    example: (props) => <Alert {...props}>test</Alert>
  }
);

/** Alert - Toast alert example
 *
 */
figma.connect(
  Alert,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=1110-2587&m=dev',
  {
    props: {
      // Group level properties
      description: figma.boolean('Description', {
        true: figma.string('✏️ Description'),
        false: undefined
      }),
      hasActions: figma.boolean('Actions'),
      // hasOverflow: figma.boolean('Overflow'),
      isExpandable: figma.boolean('Expandable')
    },
    example: (props) =>
      <Alert {...props}>{props.description}
        {props.description && <Content component={ContentVariants.p}>{props.description}</Content>}
      </Alert>
  }
);

/** Alert - Toast Alert group
 *
 */
// figma.connect(
//   ToastAlertGroup,
//   "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=1110-2821&=dev",
//   {
//     props: {
//       overflow: figma.boolean("Overflow"),
//       property1: figma.enum("Property 1", {
//         Default: "default",
//       }),
//     },
//     example: (props) => <ToastAlertGroup />,
//   },
// )