import { Masthead } from 'src/components/Masthead';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Masthead,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=2104-6642&m=dev',
  {
    props: {
      helpMenuToggle: figma.boolean('Help menu toggle'),
      settingsMenuToggle: figma.boolean('Settings menu toggle'),
      notificationBadge: figma.boolean('Notification badge'),
      contextSelector: figma.boolean('Context selector'),
      leftMenuToggle: figma.boolean('Left Menu Toggle'),
      mastheadContent: figma.enum('Masthead content', {
        'Context switcher': 'context-switcher',
        'Horizontal navigation': 'horizontal-navigation',
        None: 'none'
      }),
      sideNav: figma.enum('Side nav', {
        Open: 'open',
        Closed: 'closed'
      })
    },
    example: (props) => <Masthead />
  }
);
