import React from "react"
import { CodeEditor, Language } from '@patternfly/react-code-editor/dist/js/components/CodeEditor';
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CodeEditor,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=16994-184502&m=dev",
  {
    props: {
      action1: figma.boolean("Action 1"),
      action2: figma.boolean("Action 2"),
      action3: figma.boolean("Action 3"),
      action4: figma.boolean("Action 4"),
      action5: figma.boolean("Action 5"),
      ruler: figma.boolean("Ruler"),
      withShortcuts: figma.boolean("With Shortcuts"),
      rulerErrors: figma.boolean("Ruler & Errors"),
      showLineNumbers: figma.boolean("Show Line Numbers"),
      type: figma.enum("Type", {
        Editable: "editable",
        "Empty state": "empty-state",
        "Drag file": "drag-file",
        "Mini Map": "mini-map",
        "read only": "read-only",
      }),
    },
    example: (props) => <CodeEditor type={props.type} isLineNumbersVisible={props.showLineNumbers}  />,
  },
)
