import React from "react"
import { Skeleton } from "./Skeleton"
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Skeleton,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=790-288&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      size: figma.enum("Size", {
        S: "s",
        M: "m",
        L: "l",
        XL: "xl",
        "2XL": "2xl",
        "3XL": "3xl",
        "4XL": "4xl",
      }),
      type: figma.enum("Type", {
        Default: "default",
        Rectangle: "rectangle",
        Square: "square",
        Circle: "circle",
      }),
    },
    example: (props) => <Skeleton />,
  },
)
