import figma from "@figma/code-connect"
import { FullLogo } from "./FullLogo"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FullLogo,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2104-3689&t=TMTA4Fpy1ljK4qQP-11",
  {
    props: {},
    example: (props) => <FullLogo />,
  },
)
