import React from "react"
import { MastheadLogo } from "./MastheadLogo"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MastheadLogo,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2104-3644&t=TMTA4Fpy1ljK4qQP-11",
  {
    props: {
      type: figma.enum("Type", {
        "Logo only": "logo-only",
        "Logo + Text": "logo---text",
      }),
    },
    example: (props) => <MastheadLogo />,
  },
)
