import { MenuToggleWithButtonStyle } from './MenuToggleWithButtonStyle';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MenuToggleWithButtonStyle,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=3466-40444&t=IzSunfrnw18ti37Y-11',
  {
    props: {
      toggleText: figma.string('✏️ Toggle Text'),
      showCustomIcon: figma.boolean('Show Custom Icon'),
      showAvatar: figma.boolean('Show Avatar'),
      showBadge: figma.boolean('Show Badge'),
      showCheckbox: figma.boolean('Show Checkbox'),
      toggleText: figma.boolean('Toggle text'),
      style: figma.enum('Style', {
        Primary: 'primary',
        Secondary: 'secondary'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Disabled: 'disabled',
        Selected: 'selected'
      })
    },
    example: (props) => (
      // Documentation for MenuToggleWithButtonStyle can be found at https://www.patternfly.org/components/menu
      <MenuToggleWithButtonStyle />
    )
  }
);
