import { MenuTypeaheadToggle } from "./MenuTypeaheadToggle"
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MenuTypeaheadToggle,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2689-49976&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showChips: figma.boolean("Show Chips"),
      toggleText: figma.string("✏️ Toggle Text"),
      showAvatar: figma.boolean("Show Avatar"),
      showCheckbox: figma.boolean("Show Checkbox"),
      showBadge: figma.boolean("Show Badge"),
      showCustomIcon: figma.boolean("Show Custom Icon"),
      toggleText: figma.boolean("Toggle text"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Selected: "selected",
      }),
    },
    example: (props) => <MenuTypeaheadToggle />,
  },
)
