import React from "react"
import { AlertModal } from "./AlertModal"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AlertModal,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2940-18403&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showComponentSlot: figma.boolean("Show component slot"),
      helpIcon: figma.boolean("Help icon"),
      description: figma.boolean("Description"),
      status: figma.enum("Status", {
        Success: "success",
        Warning: "warning",
        Danger: "danger",
        Info: "info",
        "Custom alert": "custom-alert",
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
    },
    example: (props) => <AlertModal />,
  },
)
