import React from "react"
import { BasicModal } from "./BasicModal"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BasicModal,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=2937-158&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      showComponentSlot: figma.boolean("Show component slot"),
      helpIcon: figma.boolean("Help icon"),
      customIcon: figma.boolean("Custom icon"),
      description: figma.boolean("Description"),
      type: figma.enum("Type", {
        Default: "default",
        "No header": "no-header",
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
    },
    example: (props) => <BasicModal />,
  },
)
