import { Hint } from 'src/components/Hint';
import { Content } from 'src/components/Content';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Hint,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=1118-3329&m=dev',
  {
    props: {
      // titleText: figma.string('✏️ Title'),
      hintTitle: figma.boolean('Show Title ', {
        true: figma.string('✏️ Title'),
        false: undefined
      }),

      showFooter: figma.boolean('Show Footer', {
        true: figma.instance('Button'),
        false: undefined
      }),

      showBody: figma.boolean('Show Body', {
        true: figma.string('✏️ Body'),
        false: undefined
      }),
      bodyComponent: figma.boolean('Show Body', {
        true: figma.string('✏️ Body'),
        false: undefined
      }),
    },
    example: (props) => {
      const bodyComponent = 'test';

      return (
        <Hint>
          {/* {props.showBody && (<p>{props.showBody}</p>)} */}
          {/* {props.showBody && (<Content>{props.showBody}</Content>)} */}
          {bodyComponent}
        </Hint>
      )
    }
  }
);
