import React from "react"
import { Button, Hint, HintTitle, HintBody, HintFooter } from '@patternfly/react-core';
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

// figma.connect(
//   Hint,
//   "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1118-3329&t=IzSunfrnw18ti37Y-11",
//   {
//     props: {
//       showFooter: figma.boolean("Show Footer"),
//       body: figma.string("✏️ Body"),
//       title: figma.string("✏️ Title"),
//       swapButton: figma.instance("Swap button"),
//       showBody: figma.boolean("Show Body"),
//       showTitle: figma.boolean("Show Title"),
//     },
//     example: (props) => <Hint />,
//   },
// )

// import figma from '@figma/code-connect';
// import { Button, Hint, HintTitle, HintBody, HintFooter } from '@patternfly/react-core';

/**
 * PatternFly Hint integration for Figma Code Connect
 */

figma.connect(
  Button,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1291-2153&m=dev',
  {
    props: {
      type: figma.enum('Type', {
        Default: 'default',
        'Inline link external': 'inline-link-external'
      }),
      buttonText: figma.string('Text')
    },
    example: (props) => <Button type={props.type}>{props.buttonText}</Button>
  }
);

figma.connect(
  Hint,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1118-3329&t=IzSunfrnw18ti37Y-11',
  {
    props: {
      hintTitle: figma.boolean('Show Title', {
        true: <HintTitle>() => {figma.string('✏️ Title')}</HintTitle>,
        false: ''
      }),

      hintBody: figma.boolean('Show Body', {
        true: <HintBody>{figma.string('✏️ Body')}</HintBody>,
        false: ''
      }),

      hintFooter: figma.boolean('Show Footer', {
        true:
          <HintFooter>
            <Button>
              {
                figma.nestedProps('Inline link', {
                  type: figma.enum('Type', {
                    Default: 'default',
                    'Inline link external': 'inline-link-external'
                  })
                })
              }
            </Button>
          </HintFooter>,
        false: ''
      })
    },
    example: (props) => (
      <Hint>
        {props.hintTitle}
        {props.hintBody}
        {props.hintFooter}
      </Hint>
    )
  }
);

